data:
    dataset: "HighRes"
    image_size: 512
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    noise_type: "Gamma"
    random_flip: true
    rescaled: true
    num_workers: 8
    theta_0: 0.001

model:
    type: "simple"
    in_channels: 1
    out_ch: 1
    ch: 64
    ch_mult: [1, 2, 4, 4, 8]
    num_res_blocks: 2
    attn_resolutions: [32, ]
    dropout: 0.1
    var_type: fixedsmall
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 8
    n_epochs: 10000
    n_iters: 500000
    snapshot_freq: 5000
    validation_freq: 20000
    grad_accumulate: 1

sampling:
    batch_size: 32
    last_only: True

optim:
    weight_decay: 0.00005
    optimizer: "AdamW"
    lr: 0.00001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
    warmup_steps: 2000
